# serve.py serve an html file generated by backtester.py on localhost:5000

# backtester.py contains an strategy that simulate buys/sells
# from actions from google (GOOG)
# GOOG contains the google prices data, but that data is not updated

# could be cool if we scrap new data from yahoo finance or any other website
# to use it instead

# and if we have time after that, we could storage that new data to the
# mysql container and clean this mess, because we both agree that
# this code is ugly!

# remember the wisdom from uncle Bob:
'''A comment is a failure to express yourself in code.
   If you fail, then write a comment; but try not to fail.'''


import codecs
from os import system
from backtester import bt
from TESTscrape import parse
from flask import Flask


app = Flask(__name__)


@app.route('/')
def hello():
    system('python3 backtester.py')
    page = codecs.open('SmaCross.html', 'r').read()
    return page


if __name__ == '__main__':
    # app.run(host="0.0.0.0", debug=True)
    app.run(host=5000, debug=True)
